version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: database
    restart: always
    volumes:
      - ./docker/data:/var/lib/mysql