#version: '3'
#
#services:
###> doctrine/doctrine-bundle ###
#  database:
#    ports:
#      - "5432"
###< doctrine/doctrine-bundle ###
#
###> symfony/mailer ###
#  mailer:
#    image: schickling/mailcatcher
#    ports: ["1025", "1080"]
###< symfony/mailer ###
#ersion: '3'
services:
  api:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    volumes:
     - .:/var/www/html


