<?php

namespace ContainerKzogNx6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CommentsController' shared autowired service.
     *
     * @return \App\Controller\CommentsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CommentsController'] = $instance = new \App\Controller\CommentsController(($container->privates['App\\Repository\\CommentsRepository'] ?? $container->load('getCommentsRepositoryService')), ($container->privates['App\\Repository\\UsersRepository'] ?? $container->load('getUsersRepositoryService')), ($container->privates['App\\Repository\\PostsRepository'] ?? $container->load('getPostsRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\CommentsController', $container));

        return $instance;
    }
}
